import { Table } from "types/Table";

export const FRIENDSHIP_CUSTOM_TABLES: Table[] = [
  {
    title: "Rowdy group natter",
    subtitle: "A place to drink the night away",
    capacity: 8,
    columns: "1/4",
    rows: "1/3",
    reference: "Rowdy group natter",
  },
  {
    title: "Silliness salon",
    subtitle: "For the every mind already blown",
    capacity: 6,
    columns: "8/10",
    rows: "1/3",
    reference: "Silliness salon",
  },
  {
    title: "New Friends Pods",
    capacity: 4,
    columns: "1/3",
    rows: "5/6",
    reference: "New Friends Pods",
  },
  {
    title: "Philosophy Benches",
    capacity: 3,
    columns: "5",
    rows: "7/10",
    reference: "Philosophy Bench 1",
  },
  {
    capacity: 3,
    columns: "4",
    rows: "7/10",
    reference: "Philosophy Bench 2",
  },
  {
    capacity: 3,
    columns: "6",
    rows: "7/10",
    reference: "Philosophy Bench 3",
  },
  {
    title: "Fighting Cage",
    subtitle: "No chatting, only fighting",
    capacity: 4,
    columns: "1/3",
    rows: "3/4",
    reference: "Fighting Cage",
  },
  {
    title: "Solo Cage",
    subtitle: "Have a chat with yourself",
    capacity: 1,
    columns: "5",
    rows: "2",
    reference: "Solo Cage",
  },
  {
    title: "Silent Bar",
    capacity: 6,
    columns: "5/7",
    rows: "4/6",
    reference: "Silent Bar",
  },
  {
    title: "Friendship Benches",
    capacity: 2,
    columns: "9/11",
    rows: "4",
    reference: "Friendship Bench 1",
  },
  {
    capacity: 2,
    columns: "9/11",
    rows: "5",
    reference: "Friendship Bench 2",
  },
  {
    capacity: 2,
    columns: "9/11",
    rows: "6",
    reference: "Friendship Bench 3",
  },
  {
    capacity: 2,
    columns: "9/11",
    rows: "6",
    reference: "Friendship Bench 4",
  },
  {
    capacity: 2,
    columns: "9/11",
    rows: "7",
    reference: "Friendship Bench 5",
  },
];
