import { Table } from "types/Table";

export const FRIENDSHIP_CUSTOM_TABLES: Table[] = [
  {
    title: "Rowdy group natter",
    subtitle: "A place to drink the night away",
    capacity: 8,
    columns: 4,
    rows: 2,
    reference: "Rowdy group natter",
  },
  {
    title: "Silliness salon",
    subtitle: "For the every mind already blown",
    capacity: 6,
    columns: 3,
    rows: 2,
    reference: "Silliness salon",
  },
  {
    title: "New Friends Pods",
    capacity: 4,
    columns: 2,
    rows: 2,
    reference: "New Friends Pods",
  },
  {
    title: "Philosophy Bench 1",
    capacity: 3,
    columns: 1,
    rows: 3,
    reference: "Philosophy Bench 1",
  },
  {
    title: "Philosophy Bench 2",
    capacity: 3,
    columns: 1,
    rows: 3,
    reference: "Philosophy Bench 2",
  },
  {
    title: "Philosophy Bench 3",
    capacity: 3,
    columns: 1,
    rows: 3,
    reference: "Philosophy Bench 3",
  },
  {
    title: "Fighting Cage",
    subtitle: "No chatting, only fighting",
    capacity: 4,
    columns: 2,
    rows: 2,
    reference: "Fighting Cage",
  },
  {
    title: "Solo Cage",
    subtitle: "Have a chat with yourself",
    capacity: 1,
    columns: 1,
    rows: 1,
    reference: "Solo Cage",
  },
  {
    title: "Silent Bar",
    capacity: 6,
    columns: 2,
    rows: 3,
    reference: "Silent Bar",
  },
  {
    title: "Friendship Bench 1",
    capacity: 2,
    columns: 2,
    rows: 1,
    reference: "Friendship Bench 1",
  },
  {
    title: "Friendship Bench 2",
    capacity: 2,
    columns: 2,
    rows: 1,
    reference: "Friendship Bench 2",
  },
  {
    title: "Friendship Bench 3",
    capacity: 2,
    columns: 2,
    rows: 1,
    reference: "Friendship Bench 3",
  },
  {
    title: "Friendship Bench 4",
    capacity: 2,
    columns: 2,
    rows: 1,
    reference: "Friendship Bench 4",
  },
  {
    title: "Friendship Bench 5",
    capacity: 2,
    columns: 2,
    rows: 1,
    reference: "Friendship Bench 5",
  },
  {
    title: "The Kids Table",
    subtitle:
      "Have a virgin daiquiri while plotting revenge against your parents",
    capacity: 4,
    columns: 1,
    rows: 4,
    reference: "The Kids Table",
  },
  {
    title: "Philosophy Settees",
    subtitle: "Talk about what it all means",
    capacity: 5,
    columns: 3,
    rows: 2,
    reference: "Philosophy Settees",
  },
  {
    title: "The Loud Lounge",
    subtitle: "A place to drink the night away revelrously",
    capacity: 8,
    columns: 4,
    rows: 2,
    reference: "The Loud Lounge",
  },
  {
    title: "The Solitude Sofa",
    subtitle: "Have a conversation with yourself",
    capacity: 8,
    columns: 4,
    rows: 2,
    reference: "The Solitude Sofa",
  },
  {
    title: "Argumentation Station",
    subtitle: "Indulge in  strong opinions, weakly held",
    capacity: 8,
    columns: 4,
    rows: 2,
    reference: "Argumentation Station",
  },
  {
    title: "Slow date",
    subtitle: "Get to know other souls slowly",
    capacity: 2,
    columns: 1,
    rows: 2,
    reference: "Slow date",
  },
  {
    title: "Triumphant trios",
    subtitle: "Chat in threes",
    capacity: 3,
    columns: 3,
    rows: 1,
    reference: "Slow date",
  },
];
