export const SUBMIT_TEMPLATE_PAGE = "SUBMIT_TEMPLATE_PAGE";
export const SUBMIT_DETAILS_PAGE = "SUBMIT_DETAILS_PAGE";
export const SET_BANNER_URL = "SET_BANNER_URL";
export const SET_SQUARE_LOGO_URL = "SET_SQUARE_LOGO_URL";
export const SET_FORM_VALUES = "SET_FORM_VALUES";
