/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of events in the room during the overall event.
 */
export type RemoteEvent = {
  /**
   * The hour after the overall event starts that this event starts.
   */
  start_hour: number;
  /**
   * Event duration in hours.
   */
  duration_hours: number;
  /**
   * Name(s) of the event's host(s).
   */
  host: string;
  /**
   * Event name.
   */
  name: string;
  /**
   * Detailed description of the event.
   */
  text: string;
  /**
   * Interactivity level (low, medium, high), to help give guests an idea what to expect from the event.
   */
  interactivity: string;
  [k: string]: unknown;
}[];

/**
 * Co-reality Collective Party Config Schema. Made with https://jsonschema.net/.
 */
export interface ConfigRootSchema {
  /**
   * UTC seconds past epoch when the event starts.
   */
  start_utc_seconds: number;
  /**
   * Duration of the event in hours.
   */
  duration_hours: number;
  /**
   * Duration the entrance is hosted in hours.
   */
  entrance_hosted_hours: number;
  /**
   * Name of the Co-Reality event
   */
  party_name: string;
  /**
   * URL to the video to show when the entrance is unhosted.
   */
  unhosted_entry_video_url: string;
  /**
   * URL for the event map.
   */
  map_url: string;
  /**
   * SVG viewbox for the event map's SVG overlay with clickable regions. Must be 0 0 (map image width) (map image height).
   */
  map_viewbox: string;
  /**
   * Password for access to this event.
   */
  password: string;
  /**
   * Password for access to the admin site for this event.
   */
  admin_password?: string;
  /**
   * The list of rooms in the event.
   */
  rooms: RemoteRoom[];
  [k: string]: unknown;
}
/**
 * A room in the event.
 */
export interface RemoteRoom {
  /**
   * Title of the room.
   */
  name?: string;
  /**
   * A subtitle to appear next to the room name.
   */
  title: string;
  /**
   * An explanation about the purpose of this instance.
   */
  about: string;
  /**
   * An explanation about the purpose of this instance.
   */
  image: string;
  /**
   * Whether the room appears in the room list on the website.
   */
  on_list: boolean;
  /**
   * Page template used to display the room
   */
  template?: string;
  /**
   * Whether the room appears on the map on the website.
   */
  on_map: boolean;
  /**
   * An explanation about the purpose of this instance.
   */
  button_text?: string;
  /**
   * The X percentage along the map to show the attendance indicator.
   */
  attendance_x?: string;
  /**
   * The X percentage along the map to show the attendance indicator.
   */
  attendance_y?: string;
  /**
   * URL for the room.
   */
  url: string;
  /**
   * SVG path for the room's clickable region on the map.
   */
  path: string;
  events: RemoteEvent;
  [k: string]: unknown;
}
