export const TWITCH_SHORT_URL = "twitch.tv";
export const TWITCH_EMBED_URL = "https://player.twitch.tv";
export const FACEBOOK_EMBED_URL = "plugins/video.php";
export const VIMEO_EMBED_URL = "https://player.vimeo.com/video";
export const YOUTUBE_EMBED_URL = "https://www.youtube.com/embed/";
export const VIMEO_SHORT_EVENT_URL = "vimeo.com/event";
export const YOUTUBE_SHORT_URL_STRING = "youtu";
export const DEFAULT_EMBED_URL =
  "https://player.vimeo.com/video/512606583?h=84853fbd28";
