name: Deploy the changes to the AV1 env branches
on:
  push:
    branches:
      - master-av1
jobs:
  push-to-prod-envs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master-av1
          fetch-depth: 0
          token: ${{ secrets.SERVICE_USER_PAT }}
      - name: Push to sparkle production branches
        run: |
          # Temporarily disable the envs deployment

          git fetch origin master-av1

          git push origin master-av1:sparkle1
          # git push origin master-av1:sparkle2
          git push origin master-av1:sparkle3
          git push origin master-av1:sparkle4
          git push origin master-av1:sparkle5

          # git push origin master-av1:sparkle6
          # git push origin master-av1:sparkle7
          # git push origin master-av1:sparkle8
          # git push origin master-av1:sparkle9
          # git push origin master-av1:sparkle10

          git push origin master-av1:bigtop
          # git push origin master-av1:deloitte

          # git push origin master-av1:env/demo
          # git push origin master-av1:env/northwell

          # Unused envs
          # git push origin master-av1:env/memrise
          # git push origin master-av1:env/unesco
          # git push origin master-av1:env/pa
          # git push origin master-av1:env/clever
          # git push origin master-av1:env/unity

          # Unused envs with custom code
          # git push origin master-av1:env/kotr # Note: This runs custom code
          # git push origin master-av1:env/github # Note: This runs custom code.
          # git push origin master-av1:env/ohbm # Note: This runs custom code.
